#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Usage: <Git Remote>" >/dev/stderr
  exit 1
fi

tmp=$(mktemp -d)
cleanup () {
  rm -rf "$tmp"
}
trap cleanup EXIT

git clone --quiet "$1" "$tmp"
cd "$tmp"

if ! bundler outdated 2>&1 >/dev/null; then
  commitcommand bundler update >/dev/null
  git push --quiet origin
fi
