#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Usage: <Git Remote>" >/dev/stderr
  exit 1
fi

tmp=$(mktemp -d)
cleanup () {
  rm -rf "$tmp"
}
trap cleanup EXIT

git clone --quiet "$1" "$tmp"
cd "$tmp"

if ! bundler outdated >/dev/null 2>&1; then
  commitcommand bundler update
  git push origin
fi
